# Generated by Django 4.1 on 2023-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اسلایدر')),
                ('descriptions', models.CharField(max_length=200, verbose_name='توضیحات اسلایدر')),
                ('url', models.URLField(verbose_name='آدرس اسلایدر')),
                ('image', models.ImageField(upload_to='images/sliders/', verbose_name='تصویر اسلایدر')),
                ('is_show', models.BooleanField(verbose_name='نمایش داده شود ؟')),
                ('fade_up_image', models.ImageField(upload_to='images/sliders/fades', verbose_name='تصویر متحرک')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'لیست اسلایدرها',
                'ordering': ['title'],
            },
        ),
    ]
