# Generated by Django 4.1 on 2023-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('avatar', models.ImageField(upload_to='images/resume/bio/', verbose_name='تصویر آواتار')),
                ('description', models.TextField(verbose_name='متن بیوگرافی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'بیوگرافی',
                'verbose_name_plural': 'لیست بیوگرافی ها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='عنوان مهارت')),
                ('percent', models.IntegerField(verbose_name='درصد تسلط در مهارت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'لیست مهارت ها',
                'ordering': ['-percent'],
            },
        ),
    ]
