# Generated by Django 4.1 on 2023-03-27 07:00

import Resume.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(validators=[Resume.validators.min_value_validator, Resume.validators.max_value_validator], verbose_name='درصد تسلط در مهارت'),
        ),
    ]
