# Generated by Django 4.1 on 2023-04-03 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_alter_skill_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='متن بیوگرافی'),
        ),
    ]
