# Generated by Django 4.1 on 2023-04-03 07:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_alter_biography_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن بیوگرافی'),
        ),
    ]
