# Generated by Django 4.1 on 2023-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_alter_biography_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_count', models.IntegerField(verbose_name='تعداد پروژه های موفق')),
                ('working_hours', models.IntegerField(verbose_name='تعداد ساعات کاری')),
                ('rates', models.IntegerField(verbose_name='تعداد امتیازات کاربران')),
                ('customers', models.IntegerField(verbose_name='تعداد مشتری های شما')),
            ],
            options={
                'verbose_name': 'تجربه',
                'verbose_name_plural': 'لیست تجربه ها',
            },
        ),
    ]
